<script lang="ts">
	import BundleDownload from '../../components/BundleDownload.svelte';
	import { Alert, Button, Textarea } from 'flowbite-svelte';
	import { writable, type Writable } from 'svelte/store';

	import { decode } from '@msgpack/msgpack';
	import { bundles } from './bundles.js';
	import { onDestroy } from 'svelte';
	import { cleanup, invoke } from './processor.js';
	import Section from '../../components/Section.svelte';
	import Terminal from '../../components/Terminal.svelte';
	import { cli } from './wick-output.js';
	import { description, header } from '../../styles';

	let selectedBundle = 'stories15M';

	const defaultMessage = 'One day';
	let prompt = defaultMessage;
	let generationHistory: Writable<Array<{ sender: string; message: string }>> = writable([]);
	enum State {
		Ready,
		Responding,
		Finished
	}
	let state = State.Ready;
	let textDiv: HTMLDivElement;

	const scrollToBottom = async (node: HTMLDivElement) => {
		node.scroll({ top: node.scrollHeight, behavior: 'smooth' });
	};

	function autoGrow(e: Event): void {
		const target = e.target as HTMLTextAreaElement;
		target.style.height = 'inherit';
		const newHeight = target.scrollHeight;
		target.style.height = newHeight + 'px';
	}

	async function handleSend() {
		generationHistory.update((value) => [
			...value,
			{ sender: 'prompt', message: prompt.trim() },
			{ sender: 'response', message: '' }
		]);
		const aiMessageIndex = $generationHistory.length - 1;
		const output = await invoke(selectedBundle, prompt);
		state = State.Responding;
		output.subscribe({
			next(packet) {
				if (!packet.data) {
					console.log('no data');
					return;
				}
				console.log({ packet });

				const word = decode(packet.data);
				generationHistory.update((value) => {
					const updatedValue = [...value];
					updatedValue[aiMessageIndex].message += word;
					scrollToBottom(textDiv);
					return updatedValue;
				});
			},
			complete() {
				state = State.Finished;
				console.log('done');
			},
			error(err) {
				state = State.Finished;
				console.log('error', err);
			}
		});
	}

	function checkKey(e: KeyboardEvent) {
		if (e.key === 'Enter' && !e.shiftKey) {
			e.preventDefault();
			handleSend();
		}
	}

	onDestroy(cleanup);
</script>

<h1 class={header}>Object Detection in Images</h1>
<Section>
	<p class={description}>
		This demo uses the <strong>candle_ml/llama</strong> WebAssembly component to generate text using
		Llama 2 LLM models.
	</p>
	<p class={description}>
		It uses models generated by
		<a href="https://github.com/karpathy/llama2.c">Andrey Karpathy</a> and is built using the
		<a href="https://github.com/candlecorp/wick">Wick WebAssembly framework</a>, and
		<a href="https://github.com/huggingface/candle">HuggingFace's Candle library</a>.
	</p>
</Section>
<Section header="Online demo">
	<BundleDownload {bundles} bind:selectedBundle>
		<Button
			pill
			class="mt-2"
			disabled={!(bundles[selectedBundle] || {}).ready || state == State.Responding}
			on:click={handleSend}
		>
			Generate
		</Button>
	</BundleDownload>
</Section>
<Section>
	<div class="container mx-auto">
		<div class="mx-auto">
			<form on:submit|preventDefault={handleSend}>
				<label for="prompt" class="sr-only">Prompt</label>
				<Alert color="dark" class="px-3 py-2 w-full">
					<svelte:fragment slot="icon">
						<Textarea
							id="prompt"
							class="mx-4 resize-none"
							rows="1"
							placeholder={defaultMessage}
							bind:value={prompt}
							on:input={autoGrow}
							on:keydown={checkKey}
							style="height: 2.85em; max-height: 10em; overflow-y: auto;"
						/>
					</svelte:fragment>
				</Alert>
			</form>
		</div>
	</div>
	<div class="container mx-auto">
		<div class="mx-auto">
			<div class="h-96 overflow-y-auto p-4 border rounded shadow" bind:this={textDiv}>
				{#each $generationHistory as { sender, message }, index}
					{#if sender === 'prompt'}
						<span class="text-gray-400">{message}</span>
					{:else}
						{message}
						<br />
						<br />
					{/if}
				{/each}
			</div>
		</div>
	</div>
</Section>
<Section header="On the command line">
	<p class="mt-2">Use the following command to run this in your terminal:</p>
	<Terminal
		lines={[
			{
				command:
					'wick invoke candle_ml/llama2:0.0.1 generate --with=@config.json -- --prompt="One day"',
				output: ''
			}
		]}
	/>
	<p class="mt-2">For example:</p>
	<Terminal lines={cli} />
</Section>
