import type { Line } from '../../components/Terminal.svelte';

export const cli: Line[] = [
	{
		command:
			'wick invoke candle_ml/llama2:0.0.1 generate --with=@config.json -- --prompt="One day"',
		output: [
			{ payload: { value: ',' }, port: 'output' },
			{ payload: { value: ' a' }, port: 'output' },
			{ payload: { value: ' little' }, port: 'output' },
			{ payload: { value: ' girl' }, port: 'output' },
			{ payload: { value: ' named' }, port: 'output' },
			{ payload: { value: ' L' }, port: 'output' },
			{ payload: { value: 'ily' }, port: 'output' },
			{ payload: { value: ' went' }, port: 'output' },
			{ payload: { value: ' to' }, port: 'output' },
			{ payload: { value: ' the' }, port: 'output' },
			{ payload: { value: ' park' }, port: 'output' },
			{ payload: { value: ' with' }, port: 'output' },
			{ payload: { value: ' her' }, port: 'output' },
			{ payload: { value: ' mom' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' They' }, port: 'output' },
			{ payload: { value: ' saw' }, port: 'output' },
			{ payload: { value: ' a' }, port: 'output' },
			{ payload: { value: ' big' }, port: 'output' },
			{ payload: { value: ' tree' }, port: 'output' },
			{ payload: { value: ' with' }, port: 'output' },
			{ payload: { value: ' many' }, port: 'output' },
			{ payload: { value: ' leaves' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' L' }, port: 'output' },
			{ payload: { value: 'ily' }, port: 'output' },
			{ payload: { value: ' wanted' }, port: 'output' },
			{ payload: { value: ' to' }, port: 'output' },
			{ payload: { value: ' clim' }, port: 'output' },
			{ payload: { value: 'b' }, port: 'output' },
			{ payload: { value: ' the' }, port: 'output' },
			{ payload: { value: ' tree' }, port: 'output' },
			{ payload: { value: ' and' }, port: 'output' },
			{ payload: { value: ' see' }, port: 'output' },
			{ payload: { value: ' how' }, port: 'output' },
			{ payload: { value: ' high' }, port: 'output' },
			{ payload: { value: ' she' }, port: 'output' },
			{ payload: { value: ' could' }, port: 'output' },
			{ payload: { value: ' go' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' Her' }, port: 'output' },
			{ payload: { value: ' mom' }, port: 'output' },
			{ payload: { value: ' said' }, port: 'output' },
			{ payload: { value: ',' }, port: 'output' },
			{ payload: { value: ' "' }, port: 'output' },
			{ payload: { value: 'Be' }, port: 'output' },
			{ payload: { value: ' careful' }, port: 'output' },
			{ payload: { value: ',' }, port: 'output' },
			{ payload: { value: ' L' }, port: 'output' },
			{ payload: { value: 'ily' }, port: 'output' },
			{ payload: { value: '!"' }, port: 'output' },
			{ payload: { value: '\n' }, port: 'output' },
			{ payload: { value: 'L' }, port: 'output' },
			{ payload: { value: 'ily' }, port: 'output' },
			{ payload: { value: ' started' }, port: 'output' },
			{ payload: { value: ' to' }, port: 'output' },
			{ payload: { value: ' clim' }, port: 'output' },
			{ payload: { value: 'b' }, port: 'output' },
			{ payload: { value: ' the' }, port: 'output' },
			{ payload: { value: ' tree' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' She' }, port: 'output' },
			{ payload: { value: ' was' }, port: 'output' },
			{ payload: { value: ' very' }, port: 'output' },
			{ payload: { value: ' happy' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' But' }, port: 'output' },
			{ payload: { value: ' then' }, port: 'output' },
			{ payload: { value: ',' }, port: 'output' },
			{ payload: { value: ' she' }, port: 'output' },
			{ payload: { value: ' saw' }, port: 'output' },
			{ payload: { value: ' a' }, port: 'output' },
			{ payload: { value: ' small' }, port: 'output' },
			{ payload: { value: ' bird' }, port: 'output' },
			{ payload: { value: ' on' }, port: 'output' },
			{ payload: { value: ' a' }, port: 'output' },
			{ payload: { value: ' branch' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' The' }, port: 'output' },
			{ payload: { value: ' bird' }, port: 'output' },
			{ payload: { value: ' looked' }, port: 'output' },
			{ payload: { value: ' sad' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' L' }, port: 'output' },
			{ payload: { value: 'ily' }, port: 'output' },
			{ payload: { value: ' asked' }, port: 'output' },
			{ payload: { value: ' the' }, port: 'output' },
			{ payload: { value: ' bird' }, port: 'output' },
			{ payload: { value: ',' }, port: 'output' },
			{ payload: { value: ' "' }, port: 'output' },
			{ payload: { value: 'Why' }, port: 'output' },
			{ payload: { value: ' are' }, port: 'output' },
			{ payload: { value: ' you' }, port: 'output' },
			{ payload: { value: ' sad' }, port: 'output' },
			{ payload: { value: '?"' }, port: 'output' },
			{ payload: { value: ' The' }, port: 'output' },
			{ payload: { value: ' bird' }, port: 'output' },
			{ payload: { value: ' said' }, port: 'output' },
			{ payload: { value: ',' }, port: 'output' },
			{ payload: { value: ' "' }, port: 'output' },
			{ payload: { value: 'I' }, port: 'output' },
			{ payload: { value: ' lost' }, port: 'output' },
			{ payload: { value: ' my' }, port: 'output' },
			{ payload: { value: ' friend' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' I' }, port: 'output' },
			{ payload: { value: ' can' }, port: 'output' },
			{ payload: { value: "'" }, port: 'output' },
			{ payload: { value: 't' }, port: 'output' },
			{ payload: { value: ' find' }, port: 'output' },
			{ payload: { value: ' her' }, port: 'output' },
			{ payload: { value: '."' }, port: 'output' },
			{ payload: { value: '\n' }, port: 'output' },
			{ payload: { value: 'L' }, port: 'output' },
			{ payload: { value: 'ily' }, port: 'output' },
			{ payload: { value: ' wanted' }, port: 'output' },
			{ payload: { value: ' to' }, port: 'output' },
			{ payload: { value: ' help' }, port: 'output' },
			{ payload: { value: ' the' }, port: 'output' },
			{ payload: { value: ' bird' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' She' }, port: 'output' },
			{ payload: { value: ' clim' }, port: 'output' },
			{ payload: { value: 'bed' }, port: 'output' },
			{ payload: { value: ' down' }, port: 'output' },
			{ payload: { value: ' the' }, port: 'output' },
			{ payload: { value: ' tree' }, port: 'output' },
			{ payload: { value: ' and' }, port: 'output' },
			{ payload: { value: ' went' }, port: 'output' },
			{ payload: { value: ' to' }, port: 'output' },
			{ payload: { value: ' look' }, port: 'output' },
			{ payload: { value: ' for' }, port: 'output' },
			{ payload: { value: ' the' }, port: 'output' },
			{ payload: { value: ' bird' }, port: 'output' },
			{ payload: { value: "'" }, port: 'output' },
			{ payload: { value: 's' }, port: 'output' },
			{ payload: { value: ' friend' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' They' }, port: 'output' },
			{ payload: { value: ' looked' }, port: 'output' },
			{ payload: { value: ' everywhere' }, port: 'output' },
			{ payload: { value: ' but' }, port: 'output' },
			{ payload: { value: ' could' }, port: 'output' },
			{ payload: { value: ' not' }, port: 'output' },
			{ payload: { value: ' find' }, port: 'output' },
			{ payload: { value: ' them' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' Then' }, port: 'output' },
			{ payload: { value: ',' }, port: 'output' },
			{ payload: { value: ' L' }, port: 'output' },
			{ payload: { value: 'ily' }, port: 'output' },
			{ payload: { value: ' saw' }, port: 'output' },
			{ payload: { value: ' a' }, port: 'output' },
			{ payload: { value: ' big' }, port: 'output' },
			{ payload: { value: ' branch' }, port: 'output' },
			{ payload: { value: ' with' }, port: 'output' },
			{ payload: { value: ' many' }, port: 'output' },
			{ payload: { value: ' birds' }, port: 'output' },
			{ payload: { value: ' on' }, port: 'output' },
			{ payload: { value: ' it' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' She' }, port: 'output' },
			{ payload: { value: ' thought' }, port: 'output' },
			{ payload: { value: ' the' }, port: 'output' },
			{ payload: { value: ' bird' }, port: 'output' },
			{ payload: { value: "'" }, port: 'output' },
			{ payload: { value: 's' }, port: 'output' },
			{ payload: { value: ' friend' }, port: 'output' },
			{ payload: { value: ' was' }, port: 'output' },
			{ payload: { value: ' there' }, port: 'output' },
			{ payload: { value: '!' }, port: 'output' },
			{ payload: { value: ' But' }, port: 'output' },
			{ payload: { value: ' when' }, port: 'output' },
			{ payload: { value: ' she' }, port: 'output' },
			{ payload: { value: ' got' }, port: 'output' },
			{ payload: { value: ' closer' }, port: 'output' },
			{ payload: { value: ',' }, port: 'output' },
			{ payload: { value: ' she' }, port: 'output' },
			{ payload: { value: ' saw' }, port: 'output' },
			{ payload: { value: ' that' }, port: 'output' },
			{ payload: { value: ' the' }, port: 'output' },
			{ payload: { value: ' bird' }, port: 'output' },
			{ payload: { value: "'" }, port: 'output' },
			{ payload: { value: 's' }, port: 'output' },
			{ payload: { value: ' friend' }, port: 'output' },
			{ payload: { value: ' was' }, port: 'output' },
			{ payload: { value: ' not' }, port: 'output' },
			{ payload: { value: ' alone' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' The' }, port: 'output' },
			{ payload: { value: ' bird' }, port: 'output' },
			{ payload: { value: ' had' }, port: 'output' },
			{ payload: { value: ' a' }, port: 'output' },
			{ payload: { value: ' baby' }, port: 'output' },
			{ payload: { value: ' bird' }, port: 'output' },
			{ payload: { value: ' in' }, port: 'output' },
			{ payload: { value: ' its' }, port: 'output' },
			{ payload: { value: ' nest' }, port: 'output' },
			{ payload: { value: '!' }, port: 'output' },
			{ payload: { value: '\n' }, port: 'output' },
			{ payload: { value: 'L' }, port: 'output' },
			{ payload: { value: 'ily' }, port: 'output' },
			{ payload: { value: ' and' }, port: 'output' },
			{ payload: { value: ' her' }, port: 'output' },
			{ payload: { value: ' mom' }, port: 'output' },
			{ payload: { value: ' were' }, port: 'output' },
			{ payload: { value: ' surprised' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' They' }, port: 'output' },
			{ payload: { value: ' took' }, port: 'output' },
			{ payload: { value: ' the' }, port: 'output' },
			{ payload: { value: ' baby' }, port: 'output' },
			{ payload: { value: ' bird' }, port: 'output' },
			{ payload: { value: ' home' }, port: 'output' },
			{ payload: { value: ' and' }, port: 'output' },
			{ payload: { value: ' put' }, port: 'output' },
			{ payload: { value: ' it' }, port: 'output' },
			{ payload: { value: ' back' }, port: 'output' },
			{ payload: { value: ' in' }, port: 'output' },
			{ payload: { value: ' the' }, port: 'output' },
			{ payload: { value: ' tree' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' The' }, port: 'output' },
			{ payload: { value: ' baby' }, port: 'output' },
			{ payload: { value: ' bird' }, port: 'output' },
			{ payload: { value: ' was' }, port: 'output' },
			{ payload: { value: ' happy' }, port: 'output' },
			{ payload: { value: ' again' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: ' L' }, port: 'output' },
			{ payload: { value: 'ily' }, port: 'output' },
			{ payload: { value: ' learned' }, port: 'output' },
			{ payload: { value: ' that' }, port: 'output' },
			{ payload: { value: ' sometimes' }, port: 'output' },
			{ payload: { value: ',' }, port: 'output' },
			{ payload: { value: ' unexpected' }, port: 'output' },
			{ payload: { value: ' things' }, port: 'output' },
			{ payload: { value: ' can' }, port: 'output' },
			{ payload: { value: ' happen' }, port: 'output' },
			{ payload: { value: ' when' }, port: 'output' },
			{ payload: { value: ' you' }, port: 'output' },
			{ payload: { value: ' help' }, port: 'output' },
			{ payload: { value: ' others' }, port: 'output' },
			{ payload: { value: '.' }, port: 'output' },
			{ payload: { value: '<s>' }, port: 'output' },
			{ payload: { value: ' Once' }, port: 'output' },
			{ payload: { value: ' upon' }, port: 'output' },
			{ payload: { value: ' a' }, port: 'output' },
			{ payload: { value: ' time' }, port: 'output' },
			{ payload: { value: ',' }, port: 'output' },
			{ payload: { value: ' there' }, port: 'output' },
			{ payload: { value: ' was' }, port: 'output' },
			{ payload: { value: ' a' }, port: 'output' }
		]
			.map((json) => JSON.stringify(json))
			.join('\n')
	}
];
